#pragma once
#include "AutocallBase.hpp"

/**
 * @brief Airbag Autocall Product Class.
 *
 * This class implements an Autocall product with an "Airbag" mechanism at maturity.
 * Unlike a standard Autocall where losses are calculated from the initial strike (Spot0),
 * the Airbag mechanism calculates losses from a lower "Airbag Strike" (Spot0 * AirbagFloor)
 * if the protection barrier is breached.
 */
class AirbagAutocall : public AutocallBase {
public:
    /**
     * @brief Constructor for AirbagAutocall.
     *
     * @param underlying Name of the underlying asset.
     * @param observationTimes Vector of observation times (in years).
     * @param spot0 Initial spot price (Strike).
     * @param notional Notional amount.
     * @param couponRate Coupon rate (e.g., 0.05 for 5%).
     * @param callBarrier Autocall barrier level (absolute value).
     * @param protectionBarrier Protection barrier level (absolute value).
     * @param airbagFloor The factor defining the Airbag Strike (e.g., 0.7 for 70% of Spot0).
     */
    AirbagAutocall(std::string underlying,
                   std::vector<double> observationTimes,
                   double spot0,
                   double notional,
                   double couponRate,
                   double callBarrier,
                   double protectionBarrier,
                   double airbagFloor);

    /**
     * @brief Calculates the cash flows for a given path.
     *
     * @param path Simulated price path of the underlying.
     * @return std::vector<CashFlow> List of cash flows generated by the product.
     */
    std::vector<CashFlow> cashFlows(const std::vector<double>& path) const override;

private:
    /**
     * @brief Overrides the terminal redemption calculation to implement the Airbag logic.
     *
     * Logic:
     * - If FinalSpot >= ProtectionBarrier: Receive Notional (Capital Guaranteed).
     * - If FinalSpot < ProtectionBarrier: Loss is amortized starting from the Airbag Strike.
     * Redemption = Notional * (FinalSpot / (Spot0 * AirbagFloor)).
     * This reduces the loss compared to a standard PDI (Put Down and In).
     *
     * @param spotT The spot price at maturity.
     * @return The redemption amount.
     */
    double terminalRedemption(double spotT) const override;

    double airbagFloor_{}; // Factor to determine the Airbag Strike (e.g., 0.6, 0.7)
};